version: '3'

tasks:
  # Development
  build:
    desc: Compile TypeScript
    cmds:
      - npm run build

  typecheck:
    desc: Run TypeScript type checking
    cmds:
      - npm run typecheck

  # Running the application
  start:
    desc: Run the application
    cmds:
      - npm run start

  start:mock:
    desc: Run in mock mode
    cmds:
      - npm run start:mock

  # Study commands
  study:
    desc: Run a scientific study (default 10 trials, 50 cycles)
    cmds:
      - npx tsx src/index.ts --study {{.CLI_ARGS}}

  study:quick:
    desc: Run a quick study (2 trials, 5 cycles)
    cmds:
      - npx tsx src/index.ts --study --trials=2 --cycles=5

  study:full:
    desc: Run a full study (30 trials, 100 cycles)
    cmds:
      - npx tsx src/index.ts --study --trials=30 --cycles=100

  study:bazaar:
    desc: Run study with Bazaar discovery enabled
    cmds:
      - npx tsx src/index.ts --study --use-bazaar {{.CLI_ARGS}}

  study:bazaar:quick:
    desc: Quick Bazaar discovery test (2 trials, 3 cycles)
    cmds:
      - npx tsx src/index.ts --study --use-bazaar --trials=2 --cycles=3

  study:bazaar:real:
    desc: Real mode study with Bazaar (requires --budget)
    cmds:
      - npx tsx src/index.ts --study --real --use-bazaar --network=base {{.CLI_ARGS}}

  # Statistical studies (real mode, sufficient trials for significance)
  study:stats:quick:
    desc: Quick statistical validation (5 trials, 5 cycles, ~$4, p~0.15)
    cmds:
      - npx tsx src/index.ts --study --real --use-bazaar --network=base --trials=5 --cycles=5 --budget=4.00 --yes {{.CLI_ARGS}}

  study:stats:
    desc: Statistical study for significance (15 trials, 10 cycles, ~$24, p<0.05)
    cmds:
      - npx tsx src/index.ts --study --real --use-bazaar --network=base --trials=15 --cycles=10 --budget=24.00 --yes {{.CLI_ARGS}}

  study:stats:verbose:
    desc: Statistical study with verbose Bazaar debug logging
    cmds:
      - npx tsx src/index.ts --study --real --use-bazaar --network=base --trials=15 --cycles=10 --budget=24.00 --yes --verbose {{.CLI_ARGS}}

  study:stats:publication:
    desc: Publication-grade study (25 trials, 20 cycles, ~$100, p<0.01)
    cmds:
      - npx tsx src/index.ts --study --real --use-bazaar --network=base --trials=25 --cycles=20 --budget=100.00 --yes {{.CLI_ARGS}}

  # Debug commands
  agent:
    desc: Run single agent in debug mode
    cmds:
      - npx tsx src/index.ts --agent {{.CLI_ARGS}}

  agent:no-zauth:
    desc: Run agent without zauth (control condition)
    cmds:
      - npx tsx src/index.ts --agent --mode=no-zauth --cycles=5

  agent:with-zauth:
    desc: Run agent with zauth (treatment condition)
    cmds:
      - npx tsx src/index.ts --agent --mode=with-zauth --cycles=5

  # Utilities
  clean:
    desc: Remove build artifacts and results
    cmds:
      - rm -rf dist results

  help:
    desc: Show CLI help
    cmds:
      - npx tsx src/index.ts --help

  # Install dependencies
  install:
    desc: Install npm dependencies
    cmds:
      - npm install

  # Docker
  docker:build:
    desc: Build the Docker image
    cmds:
      - docker-compose build

  docker:
    desc: Start interactive Docker container with workspace and Claude auth mounted
    cmds:
      - docker-compose run --rm dev
