version: '3'

tasks:
  # Development
  build:
    desc: Compile TypeScript
    cmds:
      - npm run build

  typecheck:
    desc: Run TypeScript type checking
    cmds:
      - npm run typecheck

  # Running the application
  start:
    desc: Run the application
    cmds:
      - npm run start

  start:mock:
    desc: Run in mock mode
    cmds:
      - npm run start:mock

  # Study commands
  study:
    desc: Run a scientific study (default 10 trials, 50 cycles)
    cmds:
      - npx tsx src/index.ts --study {{.CLI_ARGS}}

  study:quick:
    desc: Run a quick study (2 trials, 5 cycles)
    cmds:
      - npx tsx src/index.ts --study --trials=2 --cycles=5

  study:full:
    desc: Run a full study (30 trials, 100 cycles)
    cmds:
      - npx tsx src/index.ts --study --trials=30 --cycles=100

  # Debug commands
  agent:
    desc: Run single agent in debug mode
    cmds:
      - npx tsx src/index.ts --agent {{.CLI_ARGS}}

  agent:no-zauth:
    desc: Run agent without zauth (control condition)
    cmds:
      - npx tsx src/index.ts --agent --mode=no-zauth --cycles=5

  agent:with-zauth:
    desc: Run agent with zauth (treatment condition)
    cmds:
      - npx tsx src/index.ts --agent --mode=with-zauth --cycles=5

  # Utilities
  clean:
    desc: Remove build artifacts and results
    cmds:
      - rm -rf dist results

  help:
    desc: Show CLI help
    cmds:
      - npx tsx src/index.ts --help

  # Install dependencies
  install:
    desc: Install npm dependencies
    cmds:
      - npm install

  # Docker
  docker:
    desc: Start interactive Docker container with workspace mounted
    cmds:
      - docker run -it --rm -v "$(pwd):/workspace" -w /workspace -e ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY alpine sh
